v1
JuramentoEl/GoBasic pull request #10
Opened 2024-11-03 21:51 UTC by JuramentoEl

2024-11-04 15:25 UTC, vladislavmass requested changes

2024-11-04 15:25 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			close(sensorChannel)
А почему горутина сама не может закрыть канал?

2024-11-04 15:25 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
Блокирующая запись в канал приведет п итогу к тому, что мы можем на ней зависнуть на вечно , а у нас есть ограничение времени работы в 1 минуту. Так что это надо исправлять

2024-11-04 15:25 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +				done <- true
Опять таки непонятно зачем это надо? Почему нельзя просто закрыть канал mean?

2024-11-04 16:16 UTC, JuramentoEl commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
Не очень понимаю, почему мы можем зависнуть в неё на вечно? Ведь через минуту в select придёт stopChannel? И как можно изменить код, что бы точно не зависнуть, так же не совсем понимаю

2024-11-07 17:59 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
Вот сюда нужно добавит селект, о котором я писал

2024-11-07 18:01 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
Тут должен быть селект. Один из кейсов которого пишет в канал channel, второй обрабатывает сигнал timeout

2024-11-07 18:05 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
```
select{
    case channel <- data.Int64():
   case <-timeout:
       return
}
```

2024-11-07 18:06 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			channel <- data.Int64()
И буфер не нужен

2024-11-07 18:21 UTC, vladislavmass approved these changes

2024-11-07 19:12 UTC, merged